language: generic

services:
  - docker

install:
  - docker build -t jctiru/react-ecommerce .

script:
  - docker run -e S3_BUCKET=$S3_BUCKET -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION jctiru/react-ecommerce
